== WebAuthn Server Example
この例は、python-fido2を使用してWebAuthnクレデンシャル登録を実装し、使用する最小限のWebサイトを示しています。
https://github.com/Yubico/python-fido2/tree/main/examples/server を
・ポート番号5000 → 5005に変更
・debugモードON
にしたものです。


=== 実行
このサンプルを実行するには、`poetry`が必要です。 
`poetry`のインストール手順については、
https://python-poetry.org/
https://qiita.com/shun198/items/97483a227f288ad58112
https://qiita.com/ksato9700/items/b893cf1db83605898d8a
が参考になります。


ディレクトリで次のコマンドを実行して、pythonライブラリ環境を準備します。

  $ poetry install

環境が作成されたら、次のコマンドを実行してサーバーを実行できます。

  $ poetry run server

サーバーが実行されているときは、WebAuthn をサポートするブラウザを使用して、
http://localhost:5005 を開いて Web サイトにアクセスします。

メモ: Webauthn には、有効な TLS 証明書の取得を伴うセキュア コンテキスト (HTTPS) が必要です。しかし、ほとんどのブラウザは
http://localhost を安全なコンテキストとして扱います。この例はデモとしてTLSなしで実行されますが、それ以外の場合は、Webauthnを使用するときは常に有効な証明書でHTTPSを使用する必要があります。

=== ウェブサイトの使用
このサイトでは、WebAuthn資格情報を登録し、認証することができます。資格情報はメモリにのみ保存され、サーバーを停止すると、登録された資格情報を「忘れる」ことになります。

==== 登録
1. `Register` リンクをクリックして認証を開始します。
2. パスキーを保存する場所を指定するダイアログが出ます。「別のスマートフォン・・・」を選択するとQRコードが表示されます。
3. QRコードをスマホのカメラで撮影すると、撮影画面に「パスキーを保存」ボタンが表示されるのでタッチします。FaceIDなどで承認すると、パスキーがスマホに保存されます。
4. 登録が成功したかどうかがポップアップ表示されます。「OK」をクリックします。
5. パスキーはiPhone(iOS18)の場合、「パスワード」アプリの「パスキー」から確認することができます。

==== 認証
メモ: 認証する前に資格情報を登録する必要があります。

1. `Authenticate` リンクをクリックして認証を開始します。
2. パスキーでサインインするか確認ダイアログがポップアップされ、パスキーの保存場所を選択する画面になります。
3. MacとiPhoneが同じApple IDで連携されている場合はiCloudキーチェーンでも認証できます。また「別のスマートフォン・・・」を選択するとQRコードが表示されます。
3. QRコードをスマホのカメラで撮影すると、撮影画面に「パスキーでサインイン」ボタンが表示されるのでタッチします。FaceIDなどで承認すると、認証されます。
4. 認証が成功したかどうかがポップアップ表示されます。`OK`.をクリックします。

=== Supporting existing U2F credentials
If you have existing U2F credentials that you wish to support, this library
offers a U2FFido2Server class which can help with this. This directory includes
a slightly altered version of the example server which uses this class to
authenticate U2F credentials as well as WebAuthn credentials. To run this
version of the server, run:

  $ poetry run server-u2f

This version allows registration both using the newer WebAuthn APIs and by using
the legacy U2F APIs, so that you can test authentication using both credential
types. The source code for this version of the server is in
`server/server_u2f.py`.

NOTE: There should be no need to support registration of new U2F credentials as
new registrations should be using the WebAuthn APIs, even for existing users.
